# Generated by Django 2.0.7 on 2020-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20200226_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='planned_invoices',
            field=models.IntegerField(default=0),
        ),
    ]
