# Generated by Django 2.0.7 on 2021-01-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_historicalcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='contract_file',
        ),
    ]
