# Generated by Django 3.1.7 on 2021-12-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20210109_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='rate',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
