# Generated by Django 3.1.7 on 2022-01-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicelist', '0011_auto_20210320_1955'),
        ('contracts', '0008_auto_20211229_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='servicelist.servicelist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicelist.servicelist'),
        ),
    ]
