# Generated by Django 3.1.7 on 2022-02-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20220112_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='planned_invoices',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='planned_invoices',
            field=models.IntegerField(default=1),
        ),
    ]
