# Generated by Django 3.1.7 on 2022-02-19 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20220202_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='date_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='date_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
